spin_version = "1"
authors = ["DeisLabs Engineering Team"]
description = "A simple spin hello world"
name = "spin-hello"
trigger = { type = "http", base = "/" }
version = "1.0.0"

[[component]]
id = "hello"
source = "spin_rust_hello.wasm"
[component.trigger]
route = "/hello"

[[component]]
id = "go-hello"
source = "spin_go_hello.wasm"
[component.trigger]
route = "/go-hello"