spin_manifest_version = 2

[application]
authors = ["DeisLabs Engineering Team"]
name = "spin-outbound-redis"
version = "1.0.0"

[variables]
redis_address = { required = true }
redis_channel = { required = true }

[[trigger.http]]
route = "hello"
component = "hello"

[component.hello]
source = "spin_outbound_redis.wasm"
allowed_outbound_hosts = ["redis://*:*"]

[component.hello.variables]
redis_address = "{{ redis_address }}"
redis_channel = "{{ redis_channel }}"

[component.hello.build]
command = "cargo build --target wasm32-wasi --release"