[build]
default-target = "x86_64-unknown-linux-musl"

[target.x86_64-unknown-linux-musl]
dockerfile.file = "./containerd-shim-spin-v1/Dockerfile"
dockerfile.context = "./containerd-shim-spin-v1/polyfill/"

[target.aarch64-unknown-linux-musl]
dockerfile.file = "./containerd-shim-spin-v1/Dockerfile"
dockerfile.context = "./containerd-shim-spin-v1/polyfill/"
