spin_version = "1"
authors = ["Suneet Nangia <suneetnangia@gmail.com>"]
name = "spin-hello"
trigger = { type = "redis", address = "redis:/localhost:6379" }
version = "1.0.0"

[[component]]
environment = { REDIS_ADDRESS = "redis://localhost:6379", REDIS_CHANNEL = "messages-out" }
id = "hello"
source = "spin_inbound_redis.wasm"
allowed_http_hosts = []
[component.trigger]
channel = "messages-in"