spin_manifest_version = 2

[application]
authors = ["Suneet Nangia <suneetnangia@gmail.com>"]
name = "spin-inbound-redis"
version = "1.0.0"

[variables]
redis_address = { required = true }
redis_channel = { required = true }

[[trigger.redis]]
address = "redis://redis-service.default.svc.cluster.local:6379"
component = "hello"

[component.hello]
source = "spin_inbound_redis.wasm"
allowed_outbound_hosts = ["redis://*:*"]

[component.hello.variables]
redis_address = "{{ redis_address }}"
redis_channel = "{{ redis_channel }}"

