spin_manifest_version = 2

[application]
name = "spin-hello"
authors = ["Kate Goldenring <kate.goldenring@fermyon.com>", "DeisLabs Engineering Team"]
description = "hello"
version = "0.1.0"

[[trigger.http]]
route = "/keyvalue"
component = "keyvalue"

[component.keyvalue]
source = "target/wasm32-wasi/release/spin_keyvalue.wasm"
allowed_http_hosts = []
key_value_stores = ["foo"]

[component.keyvalue.build]
command = "cargo build --target wasm32-wasi --release"
watch = ["src/**/*.rs", "Cargo.toml"]