ARG CROSS_BASE_IMAGE
FROM $CROSS_BASE_IMAGE

ENV CC="x86_64-linux-musl-gcc"
ENV CXX="x86_64-linux-musl-g++"
ENV AS="x86_64-linux-musl-as"
ENV AR="x86_64-linux-musl-gcc-ar"
ENV NM="x86_64-linux-musl-gcc-nm"
ENV RANLIB="x86_64-linux-musl-gcc-ranlib"
ENV LD="x86_64-linux-musl-ld"
ENV STRIP="x86_64-linux-musl-strip"