spin_manifest_version = 2

[application]
authors = ["DeisLabs Engineering Team"]
description = "A simple spin hello world"
name = "spin-hello"
version = "1.0.0"


[[trigger.http]]
route = "/hello"
component = "hello"

[[trigger.http]]
route = "/go-hello"
component = "go-hello"

[component.hello]
source = "spin_rust_hello.wasm"

[component.go-hello]
source = "spin_go_hello.wasm"