variant error {
	error-with-description(string),
}
type payload = list<u8>
type map = list<tuple<string, string>>

// Cloudevents spec: https://github.com/cloudevents/spec/blob/main/cloudevents/spec.md
// We assume the type of the data is a byte sequence. It is up to the data schema to determine
// what type of the data payload the event contains. 
record event {
	specversion: string,
	ty: string,
	source: string,
	id: string,
	data: option<payload>,
	datacontenttype: option<string>,
	dataschema: option<string>,
	subject: option<string>,
	time: option<string>,
} 
