name: release
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.*'
jobs:
  build:
    # run ci prior to release
    uses: ./.github/workflows/build.yaml
  release:
    permissions: 
      contents: write
      packages: write 
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set RELEASE_VERSION ENV var
        run: echo "RELEASE_VERSION=${GITHUB_REF:10}" >> $GITHUB_ENV
      - name: lowercase the runner OS name
        shell: bash
        run: |
          OS=$(echo "${{ runner.os }}" | tr '[:upper:]' '[:lower:]')
          echo "RUNNER_OS=$OS" >> $GITHUB_ENV
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ./target/
            ./deployments/k3d/.tmp/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: package release assets
        run: |
          mkdir _dist
          cp target/release/containerd-shim-*-v1 _dist/
          cd _dist
          tar czf containerd-wasm-shims-v1-${{ env.RELEASE_VERSION }}-${{ env.RUNNER_OS }}-amd64.tar.gz containerd-shim-*-v1
      - name: create release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ env.RELEASE_VERSION }} \
            --generate-notes \
            -p \
            _dist/containerd-wasm-shims-v1-${{ env.RELEASE_VERSION }}-${{ env.RUNNER_OS }}-amd64.tar.gz#containerd-wasm-shims-v1 \
            ./deployments/workloads/runtime.yml#example-runtimes \
            ./deployments/workloads/workload.yml#example-workloads
      - name: setup buildx
        uses: docker/setup-buildx-action@v2
      - name: login to GitHub container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build and push Spin hello world
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            ghcr.io/deislabs/containerd-wasm-shims/examples/spin-rust-hello:${{ env.RELEASE_VERSION }}
            ghcr.io/deislabs/containerd-wasm-shims/examples/spin-rust-hello:latest
          context: images/spin
      - name: build and push k3d shim image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            ghcr.io/deislabs/containerd-wasm-shims/examples/k3d:${{ env.RELEASE_VERSION }}
            ghcr.io/deislabs/containerd-wasm-shims/examples/k3d:latest
          context: deployments/k3d
      - name: clear
        if: always()
        run: |
          rm -f ${HOME}/.docker/config.json
